### ISSUE TITLE
Public Mailings - individual mailings require users login

### ISSUE THREAD

**Issue by grafis** [soonick/poMMo#126]
With "Public Mailings" set to "On" in the admin we have this URL which works perfectly from our website and as a link in our newsletters: /mailings.php

But any email that is accessed at the /mailings.php URL via the "View Mailing" link returns  a "Denied Access" message via this URL: /ajax/mailing_preview.php?mailings[]=xxx 

The prior version of poMMo allowed for the public to view the List of mailings and the individual Mailings. We can't now and I'm not sure if that is by design, related to upgrading our existing poMMo DB, or is a bug?  Any help in making the individual mailings public appreciated!  

and most importantly - thank you so much for maintaining this wonderful tool!

**Comment by grafis** [comment]
In addition to the Public Mailing viewing process changing (requiring login) it also appears to be broken.

When we tested logging in to view past mailings (which we would like to not have to do)  the following error is presented:  "Fatal error: Cannot access empty property in /home/user/public_html/pommo/classes/Pommo_Template.php on line 90"

**Comment by soonick** [comment]
Hello,

Did you upgrade from a newer version or did you make a clean install?

Regards,
Adrian

**Comment by grafis** [comment]
Hi Adrian, I upgraded from poMMo Advark PR16.1.
I worked from a clean set of poMMo master files from here, then ran the installer to upgrade the database.

**Comment by soonick** [comment]
Hey,

I verified the current functionality and it seems like I can access /mailings.php without having to log in.

If I try to access /ajax/mailing_preview.php?mailings[]=1without being logged in I get a message telling me that I must log in. After logging in I get redirected to: /ajax/mailing_preview.php with an error message (This is the bug you mention on your second comment).

If I am logged in and I try to go to /ajax/mailing_preview.php?mailings[]=1 I can see the mailing correctly. I don't know if the functionality used to be different in 16.1 but it seems to me like this page shouldn't require you to log in because you already chose to make them public.

I will fix this when I get some time. Thanks for reporting the issue.

Regards,
Adrian

**Comment by soonick** [comment]
In the meantime I found that you can do this:

/mailings.php?mail_id=1 to give public access to the mailing with id 1.

**Comment by grafis** [comment]
Tried it as a visitor and logged in as admin and get this error:
Fatal error: Cannot access empty property in /home/site/public_html/pommo/classes/Pommo_Template.php on line 90

**Comment by grafis** [comment]
And thanks for verifying, any help appreciated!

**Comment by grafis** [comment]
Thank You! Works perfectly!

**Comment by guidobora** [comment]
Hello I have the same problem with a fresh installation. 
Thanks for any help
best

**Comment by soonick** [comment]
Hello @guidobora,

Can you please open a new issue describing the problem?
