### ISSUE TITLE
Upgrade instructions from poMMo-aardvarkPR16.1

### ISSUE THREAD

**Issue by mxm** [soonick/poMMo#162]
Hi!

It's great to see that someone is working on poMMo now. It's a great piece of software that deserves to be improved further.

I don't see any upgrade instructions from the old poMMo version. Is it merely a procedure of replacing the old files with the new ones or did you make changes to the DB schema, etc? I'd be glad to write some upgrade instructions but would like to hear your opinion first.

Thanks,
Max

**Comment by soonick** [comment]
Hello Max,

It would be awesome if someone writes some documentation. It is pretty much replacing the old files but we did make some changes to the DB that can be fixed by doing this: https://github.com/soonick/poMMo/wiki/Troubleshooting#unable-to-log-in-after-upgrade (Backup your DB first just in case).

Let me know if you need more help,
Adrian
