### ISSUE TITLE
Alternative solution to fsockopen when host provider does not allow loo-back connections

### ISSUE THREAD

**Issue by zanny** [soonick/poMMo#31]
Hi,
Is there an alternative solution to fsockopen (mailctl.php) in case that the hosting provider does not allow loopback connections?
Even a hypothetical one would be appreciated.

**Comment by sebyke** [comment]
Hi there,

it is a great looking simple programme!!!! But my webhost provider said the following thing:
It looks like the issue here is related to 'loopback' connections.

Having had a look at this file:

/home/sites/myweb.co.uk/public_html/pommo/inc/classes/mailctl.php

as far as I can see - that attempts to create an HTTP connection to a page on the same server.

For security and performance reasons (as these are shared servers) these kind of connections are blocked on our servers, and they're not something we can unblock I'm afraid, it's a server wide settings.

If you can set the script to use a local file path, that is

/home/sites/myweb.co.uk/public_html

as opposed to

http://myweb.co.uk/

it should work OK though.

any help with that? please... appreciate your hard work

**Comment by soonick** [comment]
Hello sebyke,

I am not sure if the issue is as simple as you mention but I will keep this ticket open to see if there is something we can do about this.

Regards,
Adrian

**Comment by sebyke** [comment]
Thank for the reply, I am very impressed about your programme and it would fill the gap as it is a simple but very impressive software. Glad that I have found your site.

**Comment by JayB83** [comment]
Not sure if this is a proper fix, but I moved hosting and found that the new hosting didnt block fsockopen, but blocked http access through it.

I was able to work around this by editing the file '\classes\Pommo_Mail_Ctl.php' on line (about) 100 from:

OLD: $socket = fsockopen($ssl.Pommo::$_hostname, Pommo::$_hostport, $errno, $errstr, 25);
to
NEW: $socket = fsockopen('localhost', Pommo::$_hostport, $errno, $errstr, 25);

This seems to work for me, please anyone let me know if I shouldn't be doing this.

Jay

**Comment by soonick** [comment]
Hello Jay,

Thanks for sharing your fix. If that is working for you I don't see any problem with it.

I will add this suggestions somewhere in the documentation so if someone has the same problem in the future they try your suggestion.

Thanks,
Adrian

**Comment by soonick** [comment]
Created a wiki entry for this issue with your suggestion:

https://github.com/soonick/poMMo/wiki/Troubleshooting
