### ISSUE TITLE
Images not showing after sending

### ISSUE THREAD

**Issue by bachu** [soonick/poMMo#37]
Soonick, 

Me again!
I paste the newsletter, see ir perfectly in the preview, but when I receive the mail, the images are not shown.
I tried attaching the mails and using linked files to a server and couln´t make non work.

**Comment by soonick** [comment]
Hello bachu,

I imagine the problem is that when you paste into the WYSIWYG editor you are seeing an image with a reference to the image in your computer. The editor isn't design to paste complete pages into it. An HTML editor should allow you to paste HTML code with references to images on the web so it can be seen from anywhere. I opened a feature request for the HTML editor.

Thanks

**Comment by bachu** [comment]
and for now, do I have any option to send emails with images in it?

**Comment by soonick** [comment]
You can compose your messages from the WYSIWYG editor, but probably will take you some time. I will look into the HTML editor.

**Comment by soonick** [comment]
Hello bachu,

It seems that there already was a feature that allows to change from WYSIWYG to html editor

The button is below the WYSIWYG box and is names "Disable WYSIWYG"

You can paste HTML there
