### ISSUE TITLE
unable to upgrade

### ISSUE THREAD

**Issue by userlein** [soonick/poMMo#39]
when calling upgrade.php i am getting the following error with the latest poMMo version: Aardvark PR16.1 +42 from the master branch: 
Fatal error: Access to undeclared static property: Pommo::$_revision in /relativeURL/pommo/upgrade.php on line 55

**Comment by soonick** [comment]
Hello userlein,

I can't find where is the upgrade option. Can you tell me the steps you follow to get that error?
It is very possible that the option is not working because we are not hosted on the same servers that the original version was, but I would like to take a look.

Thanks for reporting this problem.

**Comment by userlein** [comment]
Hi soonick,
for upgrading the source i did the following: delete all files except config.php from webserver. Copy the extracted files from master branch to webserver. I called the file upgrade.php like http://mydomain.com/pommo/upgrade.php.
Other projects i use have regular schema changes to the database. I just thougt these changes might be reflected in the upgrade.php.

Am i right to assume that the file upgrade.php has no needed functionality and therefor can be deleted from source?

**Comment by jamesarbrown** [comment]
There have been many forks since Brices PR16... I think to make an upgrade path would now not make sense.

You could attempt to manually patch the sql across. The SQL file is found in sql/sql.schema.php and working between that and MySQL Workbench maybe you can spot the differences.

As a fix, I dont think the upgrade should be dumped... maybe useful later if development is consistent

More I would suggest

sql.schema.php Ammend to say (ie lets call Soonicks fork version 50)
INSERT INTO :::config::: VALUES ('version', 'Soonick Pommo PR0.1', 'poMMo Version', 'on', 'off');
INSERT INTO :::config::: VALUES ('key', '123456', 'Unique Identifier', 'on', 'off');
INSERT INTO :::config::: VALUES ('revision', '50', 'Internal Revision', 'on', 'off');

And then bounce any upgrade attempt, by adding this to upgrade.php

if (Pommo::$_config['revision'] < 50) {
    $logger->addErr('Upgrade path unavailable. Cannot upgrade from Aardvark PR16 or below!');
    $smarty->display('upgrade.tpl');
    Pommo::kill();
}

Ammended in jamesarbrown fork.

**Comment by soonick** [comment]
Hello,

I kind of agree with both. It is true that making an update path from PR16 would be something very difficult that would probably not be worth it.

I agree that we should still give an easy way for users to update, but I think right now is not the best time. The removal of smarty is going to change almost all the files on pommo and making an update that replaces all the files sounds dangerous to me.

I also think that we could put more thought on an update system that works a lot better than the current one. We could even make one that checks github and tells the users that there are updates available.

Let me hear your thoughts.

**Comment by jamesarbrown** [comment]
Soonick,

To stop upgrade attempts for now from old Brice stuff Suggest :-
We  :-
1) call your branch "50" (Brices last was 46)
2) Call it say "Soonick Pommo PR0.1"
3) update upgrade.php to reject upgrade attempts below 50

If that is ok with you can commit the code.

James

**Comment by soonick** [comment]
I suppose it would work for now.

Make the commit and I will pull.

Thanks.
