### ISSUE TITLE
inline (embed) pictures

### ISSUE THREAD

**Issue by grandmasterB** [soonick/poMMo#67]
Hi all!

How can I use embedded image with poMMo?
If I attach one JPG file then how can I use it in the HTML message body?

Thank you your answer!

**Comment by soonick** [comment]
Hello,

The usual practice to embed an image in the body of your message is to upload your image to a server on the Internet and link to the image from the mailing. Something like:

<img src='http://yourdomain.com/your-image.jpg'>
(I think you can do that with the WYSIWYG editor)

hope that helps,
Adrian

**Comment by grandmasterB** [comment]
First of all: Thank you soonik!

Sorry, but I know this, and it's not enough for me. 
The mailer default settings always disable the external links too. 

As I wrote: I would like to use the ATTACHED (uploaded with poMMo) images IN the HTML message body. 

Example: 

I attached: example.jpg 

I would like to use in the mail body for examle: div style="background-image:url('example.jpg');"

I hope it's clear for you! :)

**Comment by grandmasterB** [comment]
I think this is not closed issue yet... :)

**Comment by soonick** [comment]
Hello,

I understand what you are trying to do, but I am not sure how to do it. I thought that mail clients usually disabled all images, even when attached on the same mail.

I will leave this open so this can be answered by someone who knows better.

**Comment by Pudelwerfer** [comment]
You must use an absolute path in HTML-Mails. 

Eg. instead of 'image.png' use 'http://www.mydomain.com/newsletter/08-2012/img/image.png'

Maybe it helps you ...

MJ

**Comment by PigtownBooks** [comment]
Yes, but more and more browsers are blocking remote content, which not only defeats the purpose of including the image, but annoys users.  I'm trying to send out an email announcement of our new book, but when I poMMoed a test of the press release with an image of the cover art from our website, all he got was a big red x.  Not a very auspicious moment in our relationship.

**Comment by r3code** [comment]
There is some information how to do it 
http://stackoverflow.com/questions/1851728/how-to-embed-images-in-html-email
http://stackoverflow.com/questions/7288614/how-to-send-an-html-email-with-an-inline-attached-image-with-php
http://fil.ya1.ru/PHP_5_in_Practice/index.htm#page=0768667437/ch16lev1sec1.html

**Comment by soonick** [comment]
Thanks for the useful information r3code.

**Comment by soonick** [comment]
Images can be added inline now

**Comment by PigtownBooks** [comment]
Dear Adrian,

Fabulous!

Bless you.

Many thanks.

Clyde

David, Can you upgrade to latest release?

Thanks,

**Comment by altshiftzero** [comment]
I have done some research about this subject because i needed this too and it is still not fully supported in poMMo.
Easy solution that works for outlook and some other clients, but not all, is to attach the image.
Then use this code:
<img src="cid:filename.jpg" />
If you want it to work in every e-mailclient, you need to edit some things in the poMMo files.
I just edited the library phpmailer.class.php in the lib\phpmailer folder because we don't attach anything other then images. It needs editing because in the header "Content-ID" needs to be added.
PHPMailer does support this feature.

edit file class.phpmailer.php:
line.1413: $disposition =  'inline';
line.1414: $cid = $attachment[1];

Now the CID is the same as the filename and you can add above code to show the image inline without having to accept the images in every html e-mailclient.

**Comment by soonick** [comment]
Thanks @mrdemc,

I think the ideal way of doing this has something to do with base64 encoding the image and including it inline but I haven't investigated a lot about this.

**Comment by nEON7** [comment]
@mrdemc 
change this?
if (in_array($attachment[0], $incl)) { continue; }
      $filename    = $attachment[1];
      $name        = $attachment[2];
      $encoding    = $attachment[3];
      $type        = $attachment[4];
    // $disposition = 'inline';
    // $cid = $attachment[1];
     $disposition = $attachment[6];
     $cid         = $attachment[7];
      $incl[]      = $attachment[0];
      if ( $disposition == 'inline' && isset($cidUniq[$cid]) ) { continue; }
      $cidUniq[$cid] = true;

commented ones?

**Comment by PigtownBooks** [comment]
Dear Dempsey,

My apologies for the very long delay in replying, but my wife was very 
ill and recently passed away.  Only now am I catching up on back emails.

Many thanks for this suggestion, which I have forwarded on to my webmaster.

Wishing you much success with all your endeavors,

Shiva

**Comment by PigtownBooks** [comment]
Dear Adrian,

My apologies for the very long delay in replying, but my wife was very 
ill and recently passed away.  Only now am I catching up on back emails.

Dempsey van Wissen had a possible solution,  which I have forwarded on 
to my webmaster.

Thank you for your response, and wishing you much success with all your 
endeavors,

Shiva

On 12/17/2013 7:17 AM, Dempsey van Wissen wrote:
I have done some research about this subject because i needed this too.
Easy solution that works for outlook and some other clients, but not 
all, is to attach the image.
Then use this code:

If you want it to work in every e-mailclient, you need to edit some 
things in the poMMo files.
I just edited the library phpmailer.class.php in the lib\phpmailer 
folder because we don't attach anything other then images. It needs 
editing because in the header "Content-ID" needs to be added.
PHPMailer does support this feature.
edit file class.phpmailer.php:
line.1413: $disposition = 'inline';
line.1414: $cid = $attachment[1];
Now the CID is the same as the filename and you can add above code to 
show the image inline without having to accept the images in every html 
e-mailclient.
—
Reply to this email directly or view it on GitHub.
