### ISSUE TITLE
Unable to spawn background mailer

### ISSUE THREAD

**Issue by prakhar22** [soonick/poMMo#92]
Hi,

I am not able to send any mails.
It was working fine since long time.

I get following eror message

Warning: fsockopen() [function.fsockopen]: unable to connect to theinternetpeople.net:80 (Connection timed out) in /home/poMMo/classes/Pommo_Mail_Ctl.php on line 102

Notice: 1348221445 >>> Error Spawning Page! *\* Errno : Errstr: 110 : Connection timed out in /home/l/poMMo/classes/Pommo_Mail_Ctl.php on line 129

Is it to do with shared hosting?
But I have been using it since last few months and my service provider say they have not done any modifications at their end.

Request your help solving the problem.

Regards
Prash

**Comment by soonick** [comment]
Hello prakhar22,

It sound like it is a hosting issue. Some servers block connections to themselves using fsockopen, and the error message suggests that is the problem. I would start by investigating if you can use fsockopen to connect to connect to your server.

Hope it helps,
Adrian

**Comment by jamesarbrown** [comment]
Adrian,

I had the same issue just installing now. Line 100 ish of Pommo_Mail_Ctl.php

```
            $socket = fsockopen($ssl.Pommo::$_hostname, Pommo::$_host
                            $errstr, 25);
```

Resulting in (domain name removed)
[08-Aug-2013 18:46:35 UTC] PHP Warning:  fsockopen(): unable to connect to
 pommo2.mydomain.org:80 (Connection timed out) in /var/www/pommo2.mydomain.o
rg/classes/Pommo_Mail_Ctl.php on line 102

And was fixed by adding to /etc/hosts
pommo2.mydomain.org 127.0.0.1

Its something to do with the machine locally heading for its public IP and not its local IP if you do not set the hosts file. Sorry have no recommendation on a solution, but at least you know what it is.

Perhaps something in the pommo setup to provide its IP manually?

James
