### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by bartoruiz** [soonick/poMMo#99]
My server:  
Freebsd 9.0
php-5.3.18
apache-2.2.23
mysql-server-5.5.28

I have tried for days....I can install  without much trouble poMMo-aardvarkPR16.1.zip

but latest snapshot here seems to have some issues reading config and does not even let me start the installation.

this is what I get::

Notice: Undefined variable: config in /usr/home/pommo/classes/Pommo.php on line 107

Notice: Undefined variable: config in /usr/home/pommo/classes/Pommo.php on line 114

Does someone have any clue of what could be happening?

**Comment by soonick** [comment]
Are you doing a clean install?
Where did you get the latest snapshot?

**Comment by bartoruiz** [comment]
Yes, it is a clean install and have tried with different snapshots but no luck.

I got latest from your latest commit, https://github.com/soonick/poMMo/archive/bcf87e747ff67ccaa5cb9cb5d30c0d98dd76936f.zip

I tried to install Aardvark16.1 and then overwrite your files on top but the PHP outputs with a "run out of memory" error.

I didn't have this issue with another soonick-pommo installation under CentOS and I really want to debug this because it should work, Aardvark works; but there is no log created in the cache folder, already chmod 777 everything, and php output does not make sense to me.

Also tried with php5.2, same. 

I'm really running out of ideas.

**Comment by soonick** [comment]
Hello bartoruiz,

Just one more question. Are you installing on a new database or are you trying to use an old one?

For the error messages you are getting, it seems to me that your php configuration is running on strict standards mode. This would explain why you are getting notices, since poMMo is not really strict standards compliant yet.

This doesn't explain why you can't install poMMo on your server. You could try disabling strict mode on your server by adding this line to your php.ini

error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT

but I am not sure if that would work.

Have you checked your apache error logs to see if there is any useful information in there?

**Comment by bartoruiz** [comment]
soonick,

I get notices because I edited bootstrap.php with:
error_reporting(E_ALL); // [DEVELOPMENT]

I double checked apache logs and there is something new:

[Tue Nov 20 12:59:19 2012] [error] [client 148.240.83.244] PHP Fatal error:  Call to undefined function _() in /usr/home/pommo/themes/default/inc/admin.header.php on line 12

Any idea?

**Comment by soonick** [comment]
If you are installing it for development dismiss my previous comment.

It looks like you need to install gettext and php-gettext.

Let me know if that solves the problem.

**Comment by bartoruiz** [comment]
sorry for the trouble.

adding gettext extension to php seems to fix everything.

**Comment by soonick** [comment]
Awesome!

Closing this issue.

**Comment by bartoruiz** [comment]
Could you please add the check just like you check for mysql extension?

gettext is a not a default extension, at least under FreeBsd. Otherwise I will try to remember it :D

Thanks for the help.

**Comment by soonick** [comment]
That is a good idea. Reopening to add a check for gettext.
